# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: 'oss-spring-starter-$NEXT_PATCH_VERSION 🌈'
tag-template: 'oss-spring-starter-$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'documentation'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  # Changes

  $CHANGES
