spring:
  application:
    name: oss-spring-boot3-starter-sample-backend

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

oss:
  enable: true
  endpoint: ${OSS_ENDPOINT:http://127.0.0.1:9000}
  access-key: ${OSS_ACCESS_KEY:minioadmin}
  secret-key: ${OSS_SECRET_KEY:minioadmin}
  bucket-name: ${OSS_BUCKET_NAME:oss-sample}
  type: ${OSS_TYPE:minio}
  auto-create-bucket: true
  http:
    enable: true
    prefix: /api
