name: deploy
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  oss-release-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Setup Maven Central
        uses: actions/setup-java@v3
        with: # overwrite settings.xml
          java-version: '8'
          distribution: 'adopt'
          server-id: central
          server-username: CENTER_USERNAME
          server-password: CENTER_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      # 设置 jobs Maven pom 版本环境变量
      - name: Set Release version env variable
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Publish to Maven Central
        run:  mvn clean deploy -P release -Dmaven.test.skip=true
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          CENTER_USERNAME: ${{ secrets.CENTER_USERNAME }}
          CENTER_PASSWORD: ${{ secrets.CENTER_PASSWORD }}