name: Release

on:
  push:
    branches: [ main ]
    tags:
      - "v*"

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    steps:
      # 拉取源码
      - uses: actions/checkout@v3
      # 安装JDK环境
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
      - name: "Build & test"
        run: |
          mvn clean test

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          prerelease: false
          title: "Development Build"
          files: |
            *.jar